### ISSUE TITLE
Allow to work with "project" relative path

### ISSUE THREAD

**Issue by e-marchand** [4d/build4d-action#10]
for instance

```yaml
    uses: 4d/build4d-action@main
      with:
        project: ${{ github.event.repository.name }}/Project/${{ github.event.repository.name }}.4DProject
```

by adding workingdirectory to relative path

before using config path 
https://github.com/4d/build4d-action/blob/main/Project/Sources/Classes/actions.4dm#L74

Solution1: all must be done in action script
Solution2: see invalid path ie. relative path, prepend workingdirectory to try
